---
title: "SHAP Visualization"
output: html_document
---

To get the values for the plot for Cluster N: first get all the individuals in that cluster from the clusters*.txt file. 
Then in the shapValues file, for each SNP to be displayed on the plot, take the sum of the ABSOLUTE values of the shap values OVER THE INDIVIDUALS IN THAT CLUSTER.

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)
theme_set(theme_bw())
```

```{r}
clusters_classic <- read_delim('results/clusters_classic.txt', delim = '\t') %>% 
  mutate(cluster = paste('Cluster', res.Best.partition))
shap_classic <- read_delim('results/shapValues_classic.txt', delim = '\t')
clusters_resAdj <- read_delim('results/clusters_resAdj.txt', delim = '\t') %>% 
  mutate(cluster = paste('Cluster', res.Best.partition))
shap_resAdj <- read_delim('results/shapValues_resAdj.txt', delim = '\t')
```


```{r}
snps_classic <- shap_classic %>%
  select(contains('rs')) %>% 
  abs() %>%
  colMeans() %>%
  sort(decreasing = T) %>%
  names()

snps_resadj <- shap_resAdj %>%
  select(contains('rs')) %>% 
  abs() %>%
  colMeans() %>%
  sort(decreasing = T) %>%
  names()

classic_df <- clusters_classic  %>% 
  left_join(shap_classic) %>% 
  pivot_longer(contains('rs')) %>% 
  group_by(cluster, name) %>% # by cluster
  summarise(per_cluster = mean(abs(value)), .groups = 'drop') %>% 
  filter(per_cluster > 0.001)

imp_snps_classic <- unique(classic_df$name)
feat_imp_classic <- classic_df %>% 
  ggplot(aes(x = per_cluster, y = name)) +
  geom_col(fill = 'grey50', width = 0.8) +
  facet_wrap(~ cluster, ncol = 2) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05), add = c(0, 0))) +
  labs(x = 'Mean(|Shap value|)', y = NULL)+
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())
feat_imp_classic
# ggsave('figs/feat_imp_classic.pdf', feat_imp_classic,
#        width = 6, height = 3)
ggsave('figs/feat_imp_classic.ps', feat_imp_classic,
       width = 5, height = 2.5)
ggsave('figs/feat_imp_classic.png', feat_imp_classic,
       width = 5, height = 2.5)
```

```{r}
resadj_df <- clusters_resAdj %>% 
  left_join(shap_resAdj) %>% 
  pivot_longer(contains('rs')) %>% 
  group_by(cluster, name) %>% # by cluster
  summarise(per_cluster = mean(abs(value)), .groups = 'drop')

imp_snps_resadj <- resadj_df %>%
  group_by(cluster) %>%
  top_n(5) %>%
  pull(name) %>%
  unique() %>%
  shap_resAdj[, .] %>%
  abs() %>%
  colMeans() %>%
  sort(decreasing = T) %>%
  names()

# look at top 5 clusters then unite
feat_imp_resadj <- resadj_df %>% 
  filter(name %in% imp_snps_resadj) %>%
  ggplot(aes(x = per_cluster, y = name)) +
  geom_col(fill = 'grey50') +
  facet_wrap(~ cluster, ncol = 2) +
  labs(x = 'Mean(|SHAP value|)', y = NULL) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05), add = c(0, 0))) +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.spacing.x = unit(9, 'mm'),
        plot.margin = unit(c(5.5, 15.5, 5.5, 5.5), 'pt'))

feat_imp_resadj
# ggsave('figs/feat_imp_resadj.pdf', feat_imp_resadj,
#        width = 7, height = 5)
ggsave('figs/feat_imp_resadj.ps', feat_imp_resadj,
       width = 6, height = 4.5)
ggsave('figs/feat_imp_resadj.png', feat_imp_resadj,
       width = 6, height = 4.5)
```

## Classic SHAP

```{r fig.width = 12, fig.height=4}
# https://github.com/slundberg/shap/issues/29
# base_value_classic = -0.181025324381120

expit <- function(x) 1/(1+exp(-x))
untransformed_base_value_classic = -0.181025324381120
base_value_classic <- expit(untransformed_base_value_classic) # 0.4548669

# base_value_classic = 0
shap_cluster <- shap_classic[ , c('eid', snps_classic)] %>% 
  left_join(clusters_classic)

dist_mat <- shap_cluster[, snps_classic] %>% 
  as.matrix() %>% 
  dist(method = "euclidean")
clustered_shap <- hclust(dist_mat^2, method = 'complete')
myorder <- seriation:::reorder.hclust(clustered_shap, dist_mat^2, method = "OLO")

shap_reordered <- shap_cluster[myorder$order, ] %>% 
  mutate(row = row_number())

clusters_classic[myorder$order, ] %>% 
  ggplot(aes(x = 1:1489, y = res.Best.partition)) +
  geom_line()

shap_classic[, snps_classic] %>% head(30)

shap_trans <- shap_reordered %>% # TODO
  pivot_longer(contains('rs')) %>% 
  group_by(eid, row, name, cluster) %>% 
  summarise(value = sum(value), .groups = 'drop') %>% 
  pivot_wider(names_from = name) %>% 
  arrange(cluster)

# https://github.com/slundberg/shap/issues/29#issuecomment-408385378
shap_plot <- shap_trans %>% 
  mutate(
    original_explanation_distance = select(., contains("rs")) %>% rowSums(),
    total = expit(original_explanation_distance + untransformed_base_value_classic),
    min_rs = total,
    max_rs = total,
    distance_to_explain = total - base_value_classic,
    distance_coefficient = original_explanation_distance / distance_to_explain,
    across(starts_with('rs'), ~ .x / distance_coefficient)
  )

for (snp in snps_classic){ #TODO
  snp_name <- paste0(snp, '_loc')
  shap_plot <- shap_plot %>% 
    mutate(
      snp_loc = ifelse(!!sym(snp) >= 0, 
                       min_rs - !!sym(snp), 
                       max_rs - !!sym(snp)),
      min_rs = pmin(snp_loc, min_rs),
      max_rs = pmax(snp_loc, max_rs),
      !!snp_name := snp_loc
    )
}
shap_plot <- shap_plot %>% 
  select(row, cluster, total, ends_with('loc'))

p <- ggplot()
for (snp_name in rev(snps_classic)){
  snp <- paste0(snp_name, '_loc')
  new_shap <- shap_plot %>%
    mutate(fill = ifelse(total < !!sym(snp), '#048AE6', '#FF0056'),
           # color = ifelse(total < !!sym(snp), '#D1E6FA', '#FFC3D5'),
           ymin = pmin(total, !!sym(snp)),
           ymax = pmax(total, !!sym(snp))) %>% 
    arrange(row)
  rep_n <- nrow(new_shap)

  p <- p +
    geom_ribbon(
      data = new_shap, aes(x = row, ymin = total, ymax = ymax), fill = '#048AE6') +
    geom_ribbon(
      data = new_shap, aes(x = row, ymin = ymin, ymax = total), fill = '#FF0056') +
    geom_path(aes(x = row, y = !!sym(snp), group = 1),
              data = new_shap, color = 'white', alpha = 0.5) +
    geom_path(aes(x = row, y = total, group = 1), 
              data = new_shap, color = 'white', alpha = 0.5) +
    NULL
}

annotate_df <- tribble(
  ~x, ~y, ~label,
  185, 0.48 , 'rs4932178',
  900, 0.5, 'rs17636091',
  1050, 0.465, 'rs113028686'
)
shap_force <- p +
  scale_fill_identity() +
  scale_color_identity() +
  scale_alpha_identity() +
  scale_x_continuous(
    expand = expansion(0, 0), breaks = seq(0, 1400, 200)) +
  theme(panel.spacing.x = unit(0, 'mm'),
        panel.grid = element_blank()) +
  labs(y = NULL, x = NULL) +
  geom_text(data = annotate_df, 
            aes(x = x, y = y, label = label),
            color = 'white')

shap_force
ggsave('figs/shap_force_classic.png', shap_force,
       width = 9, height = 3)
ggsave('figs/shap_force_classic.ps', shap_force,
       width = 9, height = 3)

```

## resadj SHAP
```{r fig.width = 12, fig.height=4}
base_value_resadj = -0.011816386952043862
shap_cluster <- shap_resAdj[ , c('eid', snps_resadj)] %>% 
  left_join(clusters_resAdj)

dist_mat <- shap_cluster[, snps_resadj] %>% 
  as.matrix() %>% 
  dist(method = "euclidean")
clustered_shap <- hclust(dist_mat^2, method = 'complete')
myorder <- seriation:::reorder.hclust(clustered_shap, dist_mat^2, method = "OLO")

shap_reordered <- shap_cluster[myorder$order, ] %>% 
  mutate(row = row_number())

clusters_resAdj[myorder$order, ] %>% 
  ggplot(aes(x = 1:250, y = res.Best.partition)) +
  geom_line()

shap_resAdj[, snps_resadj] %>% head(30)

shap_trans <- shap_reordered %>% 
  pivot_longer(contains('rs')) %>% 
  group_by(eid, row, name, cluster) %>% 
  summarise(value = sum(value), .groups = 'drop') %>% 
  pivot_wider(names_from = name) %>% 
  arrange(cluster)

shap_plot <- shap_trans %>% 
  mutate(
    total = select(., contains("rs")) %>% rowSums() + base_value_resadj,
    min_rs = total,
    max_rs = total
  )

for (snp in snps_resadj){
  snp_name <- paste0(snp, '_loc')
  shap_plot <- shap_plot %>% 
    mutate(
      snp_loc = ifelse(!!sym(snp) >= 0, 
                       min_rs - !!sym(snp), 
                       max_rs - !!sym(snp)),
      min_rs = pmin(snp_loc, min_rs),
      max_rs = pmax(snp_loc, max_rs),
      !!snp_name := snp_loc
    )
}
shap_plot <- shap_plot %>% 
  select(row, cluster, total, ends_with('loc')) 

p <- ggplot()
for (snp_name in rev(snps_resadj)){
  snp <- paste0(snp_name, '_loc')
  new_shap <- shap_plot %>%
    mutate(fill = ifelse(total < !!sym(snp), '#048AE6', '#FF0056'),
           # color = ifelse(total < !!sym(snp), '#D1E6FA', '#FFC3D5'),
           ymin = pmin(total, !!sym(snp)),
           ymax = pmax(total, !!sym(snp))) %>% 
    arrange(row)
  rep_n <- nrow(new_shap)

  p <- p +
    geom_ribbon(
      data = new_shap, aes(x = row, ymin = total, ymax = ymax), fill = '#048AE6') +
    geom_ribbon(
      data = new_shap, aes(x = row, ymin = ymin, ymax = total), fill = '#FF0056') +
    geom_path(aes(x = row, y = !!sym(snp), group = 1),
              data = new_shap, color = 'white', alpha = 0.5) +
    geom_path(aes(x = row, y = total, group = 1), 
              data = new_shap, color = 'white', alpha = 0.5) +
    NULL
}
shap_force <- p +
  scale_fill_identity() +
  scale_color_identity() +
  scale_alpha_identity() +
  scale_x_continuous(expand = expansion(0, 0)) +
  theme(panel.spacing.x = unit(0, 'mm'),
        panel.grid = element_blank()) +
  labs(y = NULL, x = NULL)

shap_force
ggsave('figs/shap_force_resadj.png', shap_force,
       width = 9, height = 3)
ggsave('figs/shap_force_resadj.ps', shap_force,
       width = 9, height = 3)
```

```{r}
sessioninfo::session_info()
```
